version: '2'
services:
  notebook:
    build: 
      context: .
    environment:
      - DISPLAY=$DISPLAY
      - XSOCK=/tmp/.X11-unix/X0
    ports:
      - "8899:8888"
    volumes:
      - ./notebooks:/notebooks
